# Generated by Django 5.1.5 on 2025-02-14 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_craftitem_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftitem',
            name='images',
        ),
        migrations.CreateModel(
            name='CraftItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='craft_items/')),
                ('craft_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.craftitem')),
            ],
        ),
    ]
