# Generated by Django 5.1.5 on 2025-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_remove_craftitem_images_craftitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftitem',
            name='is_handmade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='craftitem',
            name='is_sustainable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='craftitem',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='craftitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
